use_frameworks!

platform :ios, '10.0'

target 'ModulOSKit_Example' do
  pod 'ModulOSKit', :path => '../'

  target 'ModulOSKit_Tests' do
    inherit! :search_paths
    
    
    pod 'Alamofire'
    pod 'SnapKit'
    pod 'Kingfisher'
    
  end
end
